# Generated by Django 3.1.5 on 2021-07-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_roomstream_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomstream',
            name='like',
        ),
    ]
